### ISSUE TITLE
LogUtils failing, or it's me?

### ISSUE THREAD

**Issue by Nnubes256** [desht/dhutils#2]
Trying to use Cuboid's fill() or any function using LogUtils:

```
[Minesweeper Reloaded] Task #27 for Minesweeper Reloaded v0.0.3 generated an exception
java.lang.NullPointerException
    at io.github.nnubes256.minesweeperreloaded.dhutils.LogUtils.finer(LogUtils.java:59)
    at io.github.nnubes256.minesweeperreloaded.dhutils.cuboid.Cuboid.fill(Cuboid.java:599)
    at io.github.nnubes256.minesweeperreloaded.DelayedArenaRemoveTask.arenaRemoveWorker(DelayedArenaRemoveTask.java:36)
    at io.github.nnubes256.minesweeperreloaded.DelayedArenaRemoveTask.run(DelayedArenaRemoveTask.java:25)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
```

The only thing that fails is the Logger. Is there a way to not trigger it?

**Comment by desht** [comment]
You need to call LogUtils.init() in your onEnable().

**Comment by Nnubes256** [comment]
Oooh...didn't had time to look into the class xd. Closing.

**Comment by desht** [comment]
No worries.  A lot of dhutils isn't documented terribly well... it all sort of evolved as I needed it rather than being carefully designed and engineered :)
